name: dart_lintz
description: A very strict set of Dart lint rules. Inspired by the likes of Java and Apex.
version: 2.0.1
repository: https://github.com/mj12358/dart-lintz
screenshots:
  - description: Dart Lintz Thumbnail
    path: assets/thumbnail.png
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - analysis
  - code-style
  - dart
  - lints

environment:
  sdk: ">=3.0.0 <4.0.0"

# NOTE: Code is not allowed in this package. Do not add dependencies.
# dependencies:
# dev_dependencies:
