name: dart_lintz
description: A very strict set of Dart lint rules. Inspired by the likes of Java and Apex.
version: 1.2.1
repository: https://github.com/mj12358/dart-lintz
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - dart
  - lints

environment:
  sdk: ">=3.0.0 <4.0.0"
# NOTE: Code is not allowed in this package. Do not add dependencies.
# dependencies:
# dev_dependencies:
